### ISSUE TITLE
rnaturalearth package vignettes can't be built unless rnaturalearthdata is already installed

### ISSUE THREAD

**Issue by JoshOBrien** [ropenscilabs/rnaturalearth#12]
... so running 

    vignette('rnaturalearth', package='rnaturalearth')

as instructed by the `README.md` won't actually work for most first time users.

**Comment by AndySouth** [comment]
Thanks @JoshOBrien I've added a suggestion to install `rnaturalearthdata` to `README.md`.

Also users should be prompted to install `rnaturalearthdata` if they use a function that requires it.

Does that work for you ? If not, can you suggest how else I can address ?
