### ISSUE TITLE
review

### ISSUE THREAD

**Issue by AndySouth** [ropenscilabs/rnaturalearth#3]
@karthik @hadley @hrbrmstr

Would you be able to take a quick look at rnaturalearth ?

Is it useful ? Is it as useful as it could be ?

The readme describes what I'm aiming for. Broadly quick access to a subset of data and a function to download other. Have I gone too far in including too many datasets making it too big ?

Thanks

(I'm away for a couple of weeks after tomorrow.)

**Comment by hadley** [comment]
I think you need to keep the data under five meg. I'd suggest that you put the fine level data a separate package - you can then make that available via a drat repo (perhaps the ROpenSci one?), or just via github.

More comments filed as separate issues

**Comment by AndySouth** [comment]
Super, thanks, will have a go at the separate issues now.

@karthik would you like this on ROpenSci ?
