### ISSUE TITLE
Extract out common get_data() function

### ISSUE THREAD

**Issue by hadley** [ropenscilabs/rnaturalearth#7]
I think something like this will work:

``` R
get_data <- function(type, scale) {
  scale <- check_scale(scale)
  getExportedValue("rnaturalearth", scale)
}
```

**Comment by AndySouth** [comment]
I have extracted out the function as suggested. 4fa72d59512011925cb09ffec3e9eb6a076ecef5

I have kept longer `scale` & `type` checking for now as I am still unsure which data to include in the package. see #3. Some scale+type combinations may be unavailable.
